# Generated by Django 3.2.7 on 2022-11-09 03:00

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, verbose_name='Product Title')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', unique=True)),
                ('ref_code', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Product Reference Code')),
                ('description', models.TextField(default='No Description Entered.', verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Price')),
                ('tax', models.DecimalField(decimal_places=2, default=0.05, help_text='Defaults to Canada, Alberta GST charge', max_digits=8, verbose_name='Tax')),
                ('product_type', models.CharField(choices=[('Deskpad', 'Deskpad'), ('Headset Holder', 'Headset Holder'), ('Lighting', 'Lighting'), ('Decorations', 'Decorations'), ('Desk Plant', 'Desk Plant'), ('Other', 'Other')], default='Other', max_length=50, verbose_name='Product Type')),
                ('cover_photo', models.ImageField(blank=True, default='/mediafiles/defaultNoImage.jpg', null=True, upload_to='', verbose_name='Primary Photo')),
                ('photo1', models.ImageField(blank=True, default='/mediafiles/defaultNoImage.jpg', null=True, upload_to='')),
                ('photo2', models.ImageField(blank=True, default='/mediafiles/defaultNoImage.jpg', null=True, upload_to='')),
                ('photo3', models.ImageField(blank=True, default='/mediafiles/defaultNoImage.jpg', null=True, upload_to='')),
                ('photo4', models.ImageField(blank=True, default='/mediafiles/defaultNoImage.jpg', null=True, upload_to='')),
                ('published_status', models.BooleanField(default=False, verbose_name='Published Status')),
                ('views', models.IntegerField(default=0, verbose_name='Total Views')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='agent_buyer', to=settings.AUTH_USER_MODEL, verbose_name='Agent, Seller or Buyer')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductViews',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(max_length=250, verbose_name='IP Address')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to='products.product')),
            ],
            options={
                'verbose_name': 'Total Views on Product',
                'verbose_name_plural': 'Total Product Views',
            },
        ),
    ]
