# Generated by Django 3.2.7 on 2022-11-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20221107_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='license',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Real Estate license'),
        ),
    ]
